Amazonweb.web/Controllers/KeywordResearchController.cs
using Amazonweb.Models;
using LinqToExcel;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity.Validation;
using System.Data.OleDb;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Amazonweb.web.Controllers
{
    public class KeywordResearchController : Controller
    {
        JwtTokenManager _JwtTokenManager = new JwtTokenManager();
        List<KeywordResearchModel> ListKeyword;
        // GET: KeywordResearch
        public ActionResult KeywordList()
        {
            ListKeyword = GetKeyword("Doll", 1);
            var ProductCategoryList = GetListCategory();
            ViewBag.ProductCategoryList = new SelectList(ProductCategoryList, "Id", "Category");
            UserModel MdUser = Services.GetLoginUser(this.ControllerContext.HttpContext, _JwtTokenManager);
            ViewBag.UserName = MdUser.UserName;
            return View(ListKeyword);
        }

        public ActionResult KeywordAdd()
        {
            UserModel MdUser = Services.GetLoginUser(this.ControllerContext.HttpContext, _JwtTokenManager);
            ViewBag.UserName = MdUser.UserName;

            return View();
        }
        // GET: KeywordResearch/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: KeywordResearch/Create
        public ActionResult Create()
        {
            var ProductCategoryList = GetListCategory();
            ViewBag.ProductCategoryList = new SelectList(ProductCategoryList, "Id", "Category");

            return View();
        }
        public List<CateoryModel> GetListCategory()
        {
            var ProductCategoryList = new List<CateoryModel>();
            var _request = "";//_JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(loginModel));

            var _response = Services.GetApiResponse(Constant.ApiCategory, "POST", _request);
            //  if (_response == null) return View();
            //---------- Get Api response stream
            using (var _result = new StreamReader(_response.GetResponseStream()))
            {

                //----------REturn response
                dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                var jsonData = JsonConvert.SerializeObject(_data);
                //var jsonUniqueName = jsonData.unique_name;
                if (json.ContainsKey("unique_name"))
                {
                    ProductCategoryList = JsonConvert.DeserializeObject<List<CateoryModel>>(json["unique_name"].ToString());
                    // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                    //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json

                }

            }
            return ProductCategoryList;

        }
        // POST: KeywordResearch/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    KeywordResearchModel objModel = new KeywordResearchModel();
                    objModel.Id = "0";
                    objModel.KeyWord = collection["KeyWord"].ToString();
                    objModel.ExactMatchSearchVolume = long.Parse(collection["ExactMatchSearchVolume"].ToString());
                    objModel.BroadMatchSearchVolume = long.Parse(collection["BroadMatchSearchVolume"].ToString());
                    objModel.CategoryId = long.Parse(collection["CategoryId"].ToString());
                    objModel.RecommendedGiveaway = long.Parse(collection["RecommendedGiveaway"].ToString());
                    objModel.HSABid = long.Parse(collection["HSABid"].ToString());
                    objModel.ExactPPCBid = long.Parse(collection["ExactPPCBid"].ToString());
                    objModel.BroadPPCBid = long.Parse(collection["BroadPPCBid"].ToString());
                    objModel.EaseToRank = long.Parse(collection["EaseToRank"].ToString());
                    objModel.RelevancyScore = long.Parse(collection["RelevancyScore"].ToString());
                    objModel.Operation = "insert";
                    SaveKeyword(objModel);
                    ListKeyword = GetKeyword("", 0);
                    return RedirectToAction("KeywordList", ListKeyword);
                }
            }
            catch (Exception ex)
            {
                string exception = ex.ToString();
            }
            return View();
        }
        private void SaveKeyword(KeywordResearchModel objModel)
        {
            var _request = _JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(objModel));
            // TODO: Add insert logic here
            var _response = Services.GetApiResponse(Constant.ApiSaveKeyword, "POST", _request);
            if (_response == null) return;
            //---------- Get Api response stream
            using (var _result = new StreamReader(_response.GetResponseStream()))
            {

                //----------REturn response
                dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                var jsonData = JsonConvert.SerializeObject(_data);
                //var jsonUniqueName = jsonData.unique_name;
                if (json.ContainsKey("unique_name"))
                {
                    // ProductCategoryList = JsonConvert.DeserializeObject<List<CateoryModel>>(json["unique_name"].ToString());
                    // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                    //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json

                   
                }

            }
        }
        // GET: KeywordResearch/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: KeywordResearch/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: KeywordResearch/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: KeywordResearch/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [Route("KeywordResearch/SerchKeyword")]
        public ActionResult GetKeywordAjx(FormCollection collection)
        {
            var ProductCategoryList = GetListCategory();
            String searchText = collection["txtSearch"];
            long categoryid = long.Parse(collection["category"]);
            KeywordResearchModel objModel = new KeywordResearchModel()
            {
                KeyWord = searchText,
                CategoryId = categoryid
            };

            var _request = _JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(objModel));
            // TODO: Add insert logic here
            var _response = Services.GetApiResponse(Constant.ApiGetkeyword, "POST", _request);
            //if (_response == null) return View();
            //---------- Get Api response stream
            using (var _result = new StreamReader(_response.GetResponseStream()))
            {

                //----------REturn response
                dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                var jsonData = JsonConvert.SerializeObject(_data);
                //var jsonUniqueName = jsonData.unique_name;
                if (json.ContainsKey("unique_name"))
                {

                    // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                    //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json
                    _data = JsonConvert.DeserializeObject<Dictionary<string, object>>(json["unique_name"].ToString());
                    if (_data.ContainsKey("Response"))
                    {
                        List<KeywordResearchModel> listKeyword = JsonConvert.DeserializeObject<List<KeywordResearchModel>>(_data["Response"].ToString());
                        ViewBag.ProductCategoryList = new SelectList(ProductCategoryList, "Id", "Category");

                        return View("KeywordList", listKeyword);
                    }
                }
                ViewBag.ProductCategoryList = new SelectList(ProductCategoryList, "Id", "Category");

                return View();
            }
        }
        public List<KeywordResearchModel> GetKeyword(string searchText, int categoryid)
        {
            KeywordResearchModel objModel = new KeywordResearchModel()
            {

                KeyWord = searchText,
                CategoryId = categoryid
            };

            var _request = _JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(objModel));
            // TODO: Add insert logic here

Amazonweb.web/Views/KeywordResearch/Create.cshtml
@model Amazonweb.Models.KeywordResearchModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>KeywordResearchModel</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.KeyWord, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.KeyWord, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.KeyWord, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ExactMatchSearchVolume, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ExactMatchSearchVolume, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExactMatchSearchVolume, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BroadMatchSearchVolume, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BroadMatchSearchVolume, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BroadMatchSearchVolume, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
        </div>
    </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.CategoryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">

            @Html.DropDownListFor(m => m.CategoryId, ViewBag.ProductCategoryList
                     as SelectList,
                     "Select Category", new { htmlAttributes = new { @class = "form-control" } })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.RecommendedGiveaway, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RecommendedGiveaway, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RecommendedGiveaway, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HSABid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.HSABid, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.HSABid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ExactPPCBid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ExactPPCBid, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ExactPPCBid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BroadPPCBid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BroadPPCBid, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BroadPPCBid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EaseToRank, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.EaseToRank, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.EaseToRank, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RelevancyScore, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RelevancyScore, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RelevancyScore, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Amazonweb.web/Views/KeywordResearch/KeywordAdd.cshtml
@model Amazonweb.Models.KeywordResearchModel

@{
    /**/

    ViewBag.Title = "KeywordAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@{

    Amazonweb.Models.UserModel user = new Amazonweb.Models.UserModel();
    user.Id = new Guid();
    user.UserName = ViewBag.UserName;
}

@Html.Partial("~/Views/Shared/PartialView/_HeaderPartial.cshtml", user)*@
<h2>KeywordAdd</h2>
@using (Html.BeginForm("KeywordUpload", "KeywordResearch", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>KeywordResearchModel</h4>
        <hr />
        <div class="form-group">

            @Html.Label("UploadExcelFile", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <h3 style="color:red;">
                    @ViewBag.Message
                </h3>
                <input type="file" id="FileUploadKeyword" name="FileUploadKeyword" />
                <input type="submit" value="KeywordUpload" />
                <a href="/KeywordResearch/DownloadExcel">Sample File Download</a>
            </div>
        </div>
    </div>
}

Amazonweb.web/Views/KeywordResearch/KeywordList.cshtml
@model IEnumerable<Amazonweb.Models.KeywordResearchModel>


@{
    ViewBag.Title = "KeywordList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

    <div class="am-pagetitle">
        <h5 class="am-title">Keyword List</h5>
        @Html.ActionLink("Create New", "Create")
    </div><!-- am-pagetitle -->
    <div class="am-pagebody">
        <script type="text/javascript">
            function Search() {
                var SelectSearch = document.getElementById("category");
                var SelectedIndex = SelectSearch.options[SelectSearch.selectedIndex].value;
                var SearchValue = document.getElementById("txtSearch").value;
                console.log("Selected Value==" + SelectedIndex + " Search VAlue" + SearchValue);
                alert("Call Search");

                $.ajax({
                    url: "../../KeywordResearch/GetKeywordAjx",
                    type: "POST",
                    data: {
                        searchText: SearchValue,
                        categoryid: SelectedIndex

                    },
                    success: function (result) {
                        console.log(result);
                    }
                });
            }
        </script>
        @using (Html.BeginForm("GetKeywordAjx", "KeywordResearch", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
        <div class="header-top">
            <div class="col-md-6 pull-left">
                <div class="form-group">
                    <input type="text" name="txtSearch" id="txtSearch" class="form-control" />
                </div>
            </div>
            <div class="col-md-3 pull-left">
                <div class="form-group">
                    <select id="category" name="category" class="form-control select2">
                        @foreach (var cat in ViewBag.ProductCategoryList)
                        {
                            <option value="@cat.Value">@cat.Text</option>
                        }

                    </select>
                </div>
            </div>
            <div class="col-md-2 pull-left">
                <input type="submit" class="btn btn-info" value="Search" />
            </div>
            </div>
            <div class="clearfix"></div>
                <div>
                    <div class="card pd-20">
                        <div class="table-responsive">
                            <table class="table table-striped mg-b-0" id="datatable1">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.KeyWord)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ExactMatchSearchVolume)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.BroadMatchSearchVolume)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.CategoryId)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.RecommendedGiveaway)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.HSABid)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.ExactPPCBid)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.BroadPPCBid)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.EaseToRank)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.RelevancyScore)
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.KeyWord)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ExactMatchSearchVolume)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.BroadMatchSearchVolume)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.CategoryId)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.RecommendedGiveaway)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.HSABid)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.ExactPPCBid)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.BroadPPCBid)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.EaseToRank)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.RelevancyScore)
                                            </td>
                                            <td>
                                                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                                                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                                                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>



                        </div><!-- table-responsive -->
                    </div>
                </div><!-- row -->
                }

            </div><!-- am-pagebody -->