Amazonweb.web/Controllers/UserProductController.cs
using Amazonweb.Controllers;
using Amazonweb.Models;
using AmzonWebApi.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Amazonweb.web.Controllers
{
    public class UserProductController : Controller
    {
        JwtTokenManager _JwtTokenManager = new JwtTokenManager();
        List<GetProductModel> ProductsList;
        public UserProductController()
        {




        }
        // GET: ProductSave
        public ActionResult Products()
        {

            ProductsList = GetProducts();
            return View(ProductsList);
        }

        private List<GetProductModel> GetProducts()
        {
            GetProductModel productSaveModel = new GetProductModel()
            {
                UserId = Services.GetLoginUser(this.ControllerContext.HttpContext, _JwtTokenManager).Id
            };
            var _request = _JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(productSaveModel));
            // TODO: Add insert logic here
            var _response = Services.GetApiResponse(Constant.ApiGetProduct, "POST", _request);
            //if (_response == null) return View();
            //---------- Get Api response stream
            using (var _result = new StreamReader(_response.GetResponseStream()))
            {

                //----------REturn response
                dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                var jsonData = JsonConvert.SerializeObject(_data);
                //var jsonUniqueName = jsonData.unique_name;
                if (json.ContainsKey("unique_name"))
                {

                    // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                    //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json
                    _data = JsonConvert.DeserializeObject<Dictionary<string, object>>(json["unique_name"].ToString());
                    if (_data.ContainsKey("Response"))
                    {
                        return JsonConvert.DeserializeObject<List<GetProductModel>>(_data["Response"].ToString());
                    }
                }
                return new List<GetProductModel>();
            }
        }
        public JsonResult GetProductASIN(String UserId)
        {
            GetProductModel productSaveModel = new GetProductModel();
            productSaveModel.UserId = Guid.Parse(UserId);//Services.GetLoginUser(this.ControllerContext.HttpContext, _JwtTokenManager).Id
            var _request = _JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(productSaveModel));
            // TODO: Add insert logic here
            var _response = Services.GetApiResponse(Constant.ApiGetProduct, "POST", _request);
            //if (_response == null) return View();
            //---------- Get Api response stream
            using (var _result = new StreamReader(_response.GetResponseStream()))
            {

                //----------REturn response
                dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                var jsonData = JsonConvert.SerializeObject(_data);
                //var jsonUniqueName = jsonData.unique_name;
                if (json.ContainsKey("unique_name"))
                {

                    // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                    //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json
                    _data = JsonConvert.DeserializeObject<Dictionary<string, object>>(json["unique_name"].ToString());
                    if (_data.ContainsKey("Response"))
                    {
                        var ListProducts = JsonConvert.DeserializeObject<List<GetProductModel>>(_data["Response"].ToString());
                        var jSonValue = JsonConvert.SerializeObject(ListProducts, Formatting.Indented);
                        //  var jSonValue= json(strserialize, JsonRequestBehavior.AllowGet);
                        return Json(jSonValue, JsonRequestBehavior.AllowGet);
                    }
                }

                return Json("data:Record Not Found");
            }
        }
        // GET: ProductSave/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ProductSave/Create
        public ActionResult AddProduct()
        {
            var ProductCategoryList = GetListCategory();
            ViewBag.ProductCategoryList = new SelectList(ProductCategoryList, "Id", "Category");

            return View();
        }
        public List<CateoryModel> GetListCategory()
        {
            var ProductCategoryList = new List<CateoryModel>();
            var _request = "";//_JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(loginModel));

            var _response = Services.GetApiResponse(Constant.ApiCategory, "POST", _request);
            //  if (_response == null) return View();
            //---------- Get Api response stream
            using (var _result = new StreamReader(_response.GetResponseStream()))
            {

                //----------REturn response
                dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                var jsonData = JsonConvert.SerializeObject(_data);
                //var jsonUniqueName = jsonData.unique_name;
                if (json.ContainsKey("unique_name"))
                {
                    ProductCategoryList = JsonConvert.DeserializeObject<List<CateoryModel>>(json["unique_name"].ToString());
                    // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                    //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json

                }

            }
            return ProductCategoryList;

        }
        // POST: ProductSave/Create
        [HttpPost]
        public ActionResult Create(ProductSaveModel productSaveModel, FormCollection collection)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    String VarIsFeacture = collection.GetValue("isFeatured").AttemptedValue;
                    productSaveModel.UserId = Services.GetLoginUser(this.ControllerContext.HttpContext, _JwtTokenManager).Id;
                    productSaveModel.Operation = "insert";
                    //ProductSaveModel productSaveModel = new ProductSaveModel()
                    //{
                    //    ASIN = collection["ASIN"].ToString(),
                    //    categoryId = long.Parse(collection["categoryId"].ToString()),
                    //    UserId = Services.GetLoginUser(this.ControllerContext.HttpContext, _JwtTokenManager).Id,
                    //    isFeatured = Convert.ToBoolean(VarIsFeacture),
                    //    Operation = "insert"
                    //};
                    var _request = _JwtTokenManager.GenerateToken(JsonConvert.SerializeObject(productSaveModel));
                    // TODO: Add insert logic here
                    var _response = Services.GetApiResponse(Constant.ApiSaveProduct, "POST", _request);
                    if (_response == null) return View();
                    //---------- Get Api response stream
                    using (var _result = new StreamReader(_response.GetResponseStream()))
                    {

                        //----------REturn response
                        dynamic _data = _JwtTokenManager.DecodeToken(JsonConvert.DeserializeObject<ResponseModel>(_result.ReadToEnd()).Response);
                        var json = JsonConvert.DeserializeObject<Dictionary<string, object>>(_data);
                        var jsonData = JsonConvert.SerializeObject(_data);
                        //var jsonUniqueName = jsonData.unique_name;
                        if (json.ContainsKey("unique_name"))
                        {
                            // ProductCategoryList = JsonConvert.DeserializeObject<List<CateoryModel>>(json["unique_name"].ToString());
                            // if (!login.Success) { ViewBag.Message = login.Response; return View(); }
                            //var jsonString = new { Id = login.Id, UserName = login.Response }; \\ not cretae a correct Formate json
                            return RedirectToAction("Products");
                        }

                    }
                }
            }
            catch
            {

            }
            return View();
        }

        // GET: ProductSave/Edit/5
        //[Route("UserProduct/Products/Edit")]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ProductSave/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductSave/Delete/5
        [Route("Products/Delete")]
        public ActionResult Delete(string Asin)
        {
            ProductSaveModel productSaveModel = new ProductSaveModel()
            {
                ASIN = Asin,

Amazonweb.web/Views/UserProduct/AddProduct.cshtml
@model Amazonweb.Models.ProductSaveModel


@{
    ViewBag.Title = "Add Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="am-pagetitle">
    <h5 class="am-title">AddProduct</h5>
</div>
<div class="am-pagebody">
    <div class="card pd-20">
        @using (Html.BeginForm("Create", "UserProduct", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.ASIN, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-5">
                        @Html.EditorFor(model => model.ASIN, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ASIN, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>


            <div class="col-md-4">
                <div class="form-group">
                    @Html.LabelFor(model => model.categoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">

                        @Html.DropDownListFor(m => m.categoryId, ViewBag.ProductCategoryList
                                 as SelectList,
                                 "Select Category", new { htmlAttributes = new { @class = "form-control select2" } })
                    </div>
                </div>
            </div>

            <div class="col-md-2">
                <div class="form-group">
                    @Html.LabelFor(model => model.isFeatured, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <div class="checkbox">
                            @Html.CheckBoxFor(model => model.isFeatured)
                            @Html.ValidationMessageFor(model => model.isFeatured, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-2">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
            </div>
            </div>
            }

            <div>
                @Html.ActionLink("Back to List", "Index")
            </div>
        </div>
</div>

        @section Scripts {
            @Scripts.Render("~/bundles/jqueryval")
        }

Amazonweb.web/Views/UserProduct/AddProductPartial.cshtml
@model Amazonweb.Models.ProductSaveModel


@{
    ViewBag.Title = "Add Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="am-pagetitle">
    <h5 class="am-title">AddProduct</h5>
</div>
<div class="am-pagebody">
    <div class="card pd-20">
        @using (Html.BeginForm("Create", "UserProduct", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.ASIN, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-5">
                            @Html.EditorFor(model => model.ASIN, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.ASIN, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>


                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.categoryId, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">

                            @Html.DropDownListFor(m => m.categoryId, ViewBag.ProductCategoryList
                                     as SelectList,
                                     "Select Category", new { htmlAttributes = new { @class = "form-control select2" } })
                        </div>
                    </div>
                </div>

                <div class="col-md-2">
                    <div class="form-group">
                        @Html.LabelFor(model => model.isFeatured, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.CheckBoxFor(model => model.isFeatured)
                                @Html.ValidationMessageFor(model => model.isFeatured, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-2">
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            </div>
        }

        <div>
            @Html.ActionLink("Back to List", "Index")
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Amazonweb.web/Views/UserProduct/Products.cshtml
@model IEnumerable<Amazonweb.Models.GetProductModel>
@{
    ViewBag.Title = "Products";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<script type="text/javascript">
    function getCheckBoxValue(ASIN, Index) {
        var asin = ASIN;
        var VarIsFetured = false;
        var ChkBoxId = "chk " + Index;
        var Chkbox = document.getElementById(ChkBoxId);
        if (Chkbox.checked == true) {
            VarIsFetured = true;
        }
        else {
            VarIsFetured = false;
        }
        $.ajax({
            url: "../../UserProduct/AddFeatured",
            type: "POST",
            data: {
                ASIN: asin,
                IsFeatured: VarIsFetured,

            },
            success: function (result) {
            }
        });
    }
</script>
<div class="am-pagetitle">
    <h5 class="am-title">Products</h5>
    @Html.ActionLink("Create New", "AddProduct")
</div>
<div class="am-pagebody">
    <div class="card pd-20">
        <div class="table-responsive">
            <table class="table table-striped mg-b-0" id="datatable1">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(model => model.ASIN)
                        </th>
                        @*<th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>*@
                        <th>
                            @Html.DisplayNameFor(model => model.categoryId)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.Category)
                        </th>
                        <th>
                            @Html.DisplayNameFor(model => model.isFeatured)
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @{int i = 0;}
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.ASIN)
                            </td>
                            @*<td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>*@
                            <td>
                                @Html.DisplayFor(modelItem => item.categoryId)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Category)
                            </td>
                            <td>

                                <input type="checkbox" onclick="getCheckBoxValue('@(item.ASIN)','@i')" checked="@(item.isFeatured)" id="chk @i" name="chk @i" />
                                @*@Html.CheckBoxFor(modelItem => item.isFeatured)*@
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                                @Html.ActionLink("Delete","Delete", new { Asin = item.ASIN })
                            </td>
                        </tr>
                        i++;
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

Amazonweb.web/Views/UserProduct/SearchProduct.cshtml
@model IEnumerable<Amazonweb.Models.GetProductModel>

@{
    ViewBag.Title = "SearchProduct";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search Product</h2>


@using (Html.BeginForm("SearchProduct", "UserProduct", FormMethod.Post))
{
    <div class="form-horizontal">

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("ASIN", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("ASIN", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessage("ASIN", "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.Label("categoryId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">

                @Html.DropDownList("categoryId", ViewBag.ProductCategoryList
                  as SelectList,
                  "Select Category", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ASIN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.categoryId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.isFeatured)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ASIN)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.categoryId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.isFeatured)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }

    </table>
}